name: Pre-push Checks

on:
  push:
    branches-ignore:
      - 'trunk'
      - 'releases-*.x'

jobs:
  pre_push:
    name: Pre-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request
        uses: actions/checkout@v3

      - name: run pre-push checks
        env:
          # https://www.kenmuse.com/blog/the-many-shas-of-a-github-pull-request/
          GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_REF: ${{ github.event.pull_request.head.ref }}
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}  # differs from GITHUB_SHA
          # GITHUB_HEAD_REF is actually the base ref (wtf) – https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
        run: |
          set -x
          git fetch origin
          TMPFILE=$(mktemp -t git-hook-input.XXXXXXXX)
          echo "${GITHUB_REF} ${GITHUB_HEAD_SHA} refs/heads/${GITHUB_BASE_REF} ${GITHUB_BASE_SHA}" > ${TMPFILE}
          for script in $(find "buildSrc/git/git-hooks/pre-push" -name '*.sh' | perl -e "print sort{(split '/', \$a)[-1] <=> (split '/', \$b)[-1]}<>"); do
            echo "checking $(basename ${script})"
            cat ${TMPFILE} | bash -x "${script}" origin "https://github.com/michaelsembwever/test-git-hooks"
          done
